"""Report generation: HTML, Markdown, JSON."""
import html
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from .db import Database, PROFILE_COLORS

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

_SEV_COLORS_HTML = {
    "critical": "#ff3a3a",
    "high": "#ff6b35",
    "medium": "#ffd166",
    "low": "#06d6a0",
    "info": "#aaaaaa",
}

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>REAPER Report — {session_name}</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e;
    --critical: #ff3a3a; --high: #ff6b35; --medium: #ffd166;
    --low: #06d6a0; --info: #888;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 24px; }}
  h1 {{ font-size: 2rem; color: #58a6ff; margin-bottom: 4px; }}
  h2 {{ font-size: 1.2rem; color: var(--muted); margin: 32px 0 12px; border-bottom: 1px solid var(--border); padding-bottom: 6px; }}
  .meta {{ color: var(--muted); font-size: .9rem; margin-bottom: 24px; }}
  .meta span {{ margin-right: 20px; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 12px; margin-bottom: 32px; }}
  .card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 16px; text-align: center; }}
  .card .count {{ font-size: 2.4rem; font-weight: 700; }}
  .card .label {{ font-size: .8rem; color: var(--muted); text-transform: uppercase; letter-spacing: .05em; }}
  table {{ width: 100%; border-collapse: collapse; font-size: .9rem; }}
  th {{ text-align: left; padding: 8px 12px; border-bottom: 2px solid var(--border); color: var(--muted); text-transform: uppercase; font-size: .75rem; letter-spacing: .05em; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }}
  tr:hover td {{ background: var(--surface); }}
  .sev {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: .75rem; font-weight: 600; text-transform: uppercase; color: #000; }}
  .sev-critical {{ background: var(--critical); }}
  .sev-high {{ background: var(--high); }}
  .sev-medium {{ background: var(--medium); }}
  .sev-low {{ background: var(--low); }}
  .sev-info {{ background: var(--info); color: #fff; }}
  pre.evidence {{ background: #000; border-radius: 4px; padding: 8px; font-size: .78rem; white-space: pre-wrap; word-break: break-all; color: #7ee787; max-height: 120px; overflow-y: auto; }}
  footer {{ margin-top: 48px; color: var(--muted); font-size: .8rem; }}
</style>
</head>
<body>
<h1>&#9760; REAPER Report</h1>
<div class="meta">
  <span>Session: <strong>{session_name}</strong></span>
  <span>Target: <strong>{target}</strong></span>
  <span>Profile: <strong>{profile}</strong></span>
  <span>Generated: <strong>{generated_at}</strong></span>
</div>

<h2>Summary</h2>
<div class="summary-grid">
{summary_cards}
</div>

<h2>Findings ({total_findings})</h2>
<table>
  <thead>
    <tr>
      <th>#</th><th>Severity</th><th>Module</th><th>Title</th><th>Target</th><th>Evidence</th>
    </tr>
  </thead>
  <tbody>
{finding_rows}
  </tbody>
</table>

<h2>Module Runs</h2>
<table>
  <thead>
    <tr><th>Module</th><th>Status</th><th>Started</th><th>Duration</th><th>Command</th></tr>
  </thead>
  <tbody>
{run_rows}
  </tbody>
</table>

<footer>Generated by REAPER v1.0 &mdash; {generated_at}</footer>
</body>
</html>"""


def _duration(started: str, completed: Optional[str]) -> str:
    if not completed:
        return "—"
    try:
        s = datetime.fromisoformat(started)
        c = datetime.fromisoformat(completed)
        secs = int((c - s).total_seconds())
        if secs < 60:
            return f"{secs}s"
        return f"{secs // 60}m{secs % 60}s"
    except Exception:
        return "?"


def generate_report(
    db: Database,
    session_id: int,
    fmt: str = "html",
    output_path: Optional[str] = None,
) -> str:
    session = db.get_session(session_id)
    if not session:
        raise ValueError(f"Session {session_id} not found")

    findings = db.get_findings(session_id)
    runs = db.get_module_runs(session_id)
    counts = db.findings_count(session_id)

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    # Strip anything but a safe charset so a session name can't escape the
    # reports directory via path separators or '..' segments.
    slug = re.sub(r"[^A-Za-z0-9._-]+", "_", session["name"]).strip("._").lower() or "session"

    if output_path is None:
        reports_dir = Path.home() / ".reaper" / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        ext = {"html": "html", "md": "md", "json": "json"}.get(fmt, fmt)
        output_path = str(reports_dir / f"reaper_{slug}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.{ext}")

    if fmt == "html":
        content = _render_html(session, findings, runs, counts, now)
    elif fmt == "md":
        content = _render_markdown(session, findings, runs, counts, now)
    else:
        content = _render_json(session, findings, runs, counts, now)

    Path(output_path).write_text(content, encoding="utf-8")
    return output_path


def _render_html(session, findings, runs, counts, now) -> str:
    total = sum(counts.values())

    # Summary cards
    cards_html = ""
    for sev in _SEVERITY_ORDER:
        cnt = counts.get(sev, 0)
        color = _SEV_COLORS_HTML.get(sev, "#888")
        cards_html += (
            f'  <div class="card">'
            f'<div class="count" style="color:{color}">{cnt}</div>'
            f'<div class="label">{sev}</div></div>\n'
        )
    cards_html += f'  <div class="card"><div class="count" style="color:#58a6ff">{total}</div><div class="label">Total</div></div>\n'

    # Finding rows — all scanned/user-controlled fields are HTML-escaped;
    # `sev` comes from the closed Severity enum so it's safe as-is.
    rows = ""
    for i, f in enumerate(findings, 1):
        sev = f["severity"]
        evi = html.escape(f["evidence"][:200]) if f["evidence"] else ""
        rows += (
            f'  <tr>'
            f'<td>{i}</td>'
            f'<td><span class="sev sev-{sev}">{sev}</span></td>'
            f'<td>{html.escape(f["module"])}</td>'
            f'<td>{html.escape(f["title"][:120])}</td>'
            f'<td>{html.escape(f["target"][:60])}</td>'
            f'<td><pre class="evidence">{evi}</pre></td>'
            f'</tr>\n'
        )

    # Run rows — `status` comes from the closed set completed/failed/running.
    run_rows = ""
    for r in runs:
        dur = _duration(r["started_at"], r.get("completed_at"))
        status_color = {"completed": "#06d6a0", "failed": "#ff3a3a", "running": "#ffd166"}.get(r["status"], "#888")
        cmd_short = html.escape(r["command"][:80])
        run_rows += (
            f'  <tr>'
            f'<td>{html.escape(r["module_name"])}</td>'
            f'<td style="color:{status_color}">{r["status"]}</td>'
            f'<td>{r["started_at"][:16]}</td>'
            f'<td>{dur}</td>'
            f'<td><code>{cmd_short}</code></td>'
            f'</tr>\n'
        )

    return _HTML_TEMPLATE.format(
        session_name=session["name"],
        target=session["target"],
        profile=session["profile"],
        generated_at=now,
        summary_cards=cards_html,
        total_findings=total,
        finding_rows=rows,
        run_rows=run_rows,
    )


def _render_markdown(session, findings, runs, counts, now) -> str:
    total = sum(counts.values())
    lines = [
        f"# REAPER Report — {session['name']}",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Target | `{session['target']}` |",
        f"| Profile | {session['profile']} |",
        f"| Generated | {now} |",
        "",
        "## Summary",
        "",
    ]
    for sev in _SEVERITY_ORDER:
        cnt = counts.get(sev, 0)
        lines.append(f"- **{sev.upper()}**: {cnt}")
    lines += [f"- **TOTAL**: {total}", ""]

    lines += [
        "## Findings",
        "",
        "| # | Severity | Module | Title | Target |",
        "|---|----------|--------|-------|--------|",
    ]
    for i, f in enumerate(findings, 1):
        title = f["title"].replace("|", "\\|")[:80]
        lines.append(f"| {i} | {f['severity'].upper()} | {f['module']} | {title} | {f['target'][:50]} |")

    lines += ["", "## Module Runs", "", "| Module | Status | Duration | Command |", "|--------|--------|----------|---------|"]
    for r in runs:
        dur = _duration(r["started_at"], r.get("completed_at"))
        cmd = r["command"][:60].replace("|", "\\|")
        lines.append(f"| {r['module_name']} | {r['status']} | {dur} | `{cmd}` |")

    lines += ["", f"---", f"*Generated by REAPER v1.0 — {now}*"]
    return "\n".join(lines)


def _render_json(session, findings, runs, counts, now) -> str:
    data = {
        "generated_at": now,
        "session": dict(session),
        "summary": counts,
        "total_findings": sum(counts.values()),
        "findings": findings,
        "module_runs": [
            {**r, "duration": _duration(r["started_at"], r.get("completed_at"))}
            for r in runs
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False)
